### ISSUE TITLE
question about several pip packages

### ISSUE THREAD

**Issue by heipi33** [colorful-liyu/3DQD#10]
chamfer-3d==0.0.0， clip==1.0，emd-ext==0.0.0，pointnet2-ops==3.0.0
i can't pip install these packages, so i can't run the unconditional generation, where can i get these pkgs?

**Comment by colorful-liyu** [comment]
Please consider installing these pkgs:
 
https://github.com/ThibaultGROUEIX/ChamferDistancePytorch

https://github.com/daerduoCarey/PyTorchEMD

https://github.com/mit-han-lab/pvcnn/tree/master/modules

https://github.com/openai/CLIP

**Comment by colorful-liyu** [comment]
Specifically,
You can install CLIP by `pip install git+https://github.com/openai/CLIP.git `
You can install pointnet2-ops by `pip install git+https://gitee.com/Fukexue/Pointnet2_PyTorch.git@acda965224f35854bc331cd5fe140393216b0a71#subdirectory=pointnet2_ops_lib`.

As for emd-ext, please execute the following commands.
```
cd metrics/pvd_metrics/PyTorchEMD
python setup.py install
cp build/**/emd_cuda.cpython-38-x86_64-linux-gnu.so .
```

For chamfer-3d,
```
cd metrics/pvd_metrics/ChamferDistancePytorch/chamfer3D
python setup.py install
```

**Comment by heipi33** [comment]
thanks a lot

**Comment by colorful-liyu** [comment]
No problem. Please feel free to contact us.

**Comment by heipi33** [comment]
I've already set the environment and try to run the evaluation demo scripts to test the infer. ( unconditional generation/shape completion/text-driven generation). But all of them end up with a similar error "No such file or directory: '../dataset/ShapeNet/info.json'".

Does the unconditional generation depends on the preprocessed dataset? I've download the raw ShapeNetCoreV1 dataset, but there is no "info.jason" file, where can I get this file?

besides, it seems that the download url(OneDrive,ShapeNet) of the preprocess data is unavailabe now, could u update it ?

**Comment by colorful-liyu** [comment]
The unconditional generation script actually generates shapes and calculates the metrics with the preprocessed dataset. That's why `'../dataset/ShapeNet/info.json'` is needed.

I can download preprocessed dataset from the url https://1drv.ms/u/s!ApvxZzWKg6qdhAa16a5AqsPjQen4?e=0pr3fs

**Comment by heipi33** [comment]
![image](https://github.com/colorful-liyu/3DQD/assets/81794239/beb832d5-f4ae-43c6-8ddd-06b7cb5525b0)
I have trouble openning this url.
By the way, thanks for replying！

**Comment by colorful-liyu** [comment]
Can you try this URL https://1drv.ms/u/s!ApvxZzWKg6qdhAaJBq1qFa1sIqYV?e=8spCDn

**Comment by heipi33** [comment]
I can download it now, thanks!

**Comment by heipi33** [comment]
Hi, I successfully run the eval_scripts.
I have another question: how can I genearate samples using the pretrained model?
