### ISSUE TITLE
How to use the pretrained models to generate 3d model and then visualize it?

### ISSUE THREAD

**Issue by heipi33** [colorful-liyu/3DQD#12]
Hi, I successfully run the eval_uncond.py which i believe it can unconditionally generate a 3d model like obj or other formats. But I only find a .npz file. Is it the output of unconditional gen? 
Besides, where can I find the codes for just generating without evaluating, and then visualize the output file?
Thanks for your replying for my former issue, it's a really great work!

**Comment by colorful-liyu** [comment]
Hi, .npz file is the SDF format of the output. Please refer to the function `convert_points` in `metrics/uncond_metrics.py` to convert it into mesh or point clouds

**Comment by heipi33** [comment]
Hi, i tried to modify the `evaluation_scripts/eval_uncond.py `
 to let it generate samples without evaluating, but i find that they generate the same output file.
I have another question:
1)How can i  generate different samples from the pretrained models, like random generating? Is there any scripts or how can I change the `eval_uncond.py` to just generate samples without evaluating?

**Comment by colorful-liyu** [comment]
maybe you need to let seed be random. I set the seed to a fixed number for evaluation

**Comment by heipi33** [comment]
thanks, I solve the problem!
