### ISSUE TITLE
Consultation reports an error when running ‘eval_uncond.py’, prompting ‘RuntimeError: Unrecognized tensor type ID: Autocast’

### ISSUE THREAD

**Issue by rain2050** [colorful-liyu/3DQD#16]
**Thanks to the excellent work of open source, when running ‘eval_uncond.py’, the following error is prompted. Have you ever encountered a similar situation and how did you resolve it? Looking forward to your reply.**

Pairwise EMD-CD:   0%|          | 0/1311 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/rain/3DQD/evaluation_scripts/eval_uncond.py", line 162, in <module>
    results = EVAL(opt, model, sdf_files, gen_num=len(model_list), gen_bs = 16, save_flag = True, guidew = opt.guidew, class_label=1, class_desc=cats) # 795, 1311, 626
  File "/home/rain/anaconda3/envs/3dqd/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/home/rain/3DQD/evaluation_scripts/eval_uncond.py", line 69, in EVAL
    results = compute_all_metrics(opt.device, gen_list, sdf_files, 48, opt.mode, logger, opt.EMD_flag, num_points=opt.num_points, class_label=class_desc)
  File "/home/rain/3DQD/metrics/uncond_metrics.py", line 41, in compute_all_metrics
    M_rs_cd, M_rs_emd = _pairwise_EMD_CD_(sample_pcs, ref_pcs, batch_size, EMD_flag, verbose=True)
  File "/home/rain/3DQD/metrics/uncond_metrics.py", line 202, in _pairwise_EMD_CD_
    emd_batch = EMD(sample_batch_exp, ref_batch, transpose=False)
  File "/home/rain/3DQD/metrics/pvd_metrics/PyTorchEMD/emd.py", line 44, in earth_mover_distance
    cost = EarthMoverDistanceFunction.apply(xyz1, xyz2)
  File "/home/rain/3DQD/metrics/pvd_metrics/PyTorchEMD/emd.py", line 11, in forward
    match = emd_cuda.approxmatch_forward(xyz1, xyz2)
RuntimeError: Unrecognized tensor type ID: Autocast

**Comment by colorful-liyu** [comment]
It looks like you compiled a certain project (PyTorchEMD I guess) from source based on a certain version of PyTorch, and then changed to another PyTorch version. Confirming that the PyTorch version meets the installation requirements in the readme and reinstalling PyTorchEMD may solve the problem.

**Comment by rain2050** [comment]
Thanks for your reply, I changed the '--EMD flag' to 'False' and I can run the 'eval_uncond.py' code. Don't know if it will have any impact. Will it affect subsequent network training? Looking forward to your reply.

![1710385035666](https://github.com/colorful-liyu/3DQD/assets/39472362/24d8cd4d-5b7a-4fde-b438-250647161722)

**Comment by colorful-liyu** [comment]
--EMD flag is used to activate the function that measures EMD in the test script. If you set it to false, the EMD will not be measured and return zero. Other parts of the script will not be involved.

**Comment by rain2050** [comment]
Thank you for your reply and wish you good luck in your research.
