### ISSUE TITLE
dataset sdf_v1_64

### ISSUE THREAD

**Issue by zjl520-l** [colorful-liyu/3DQD#2]
你好，我从disn下载sdf_v1数据集但是您的代码需要sdf_v1_64数据集，两者的数据尺寸不一样，请问后者应该在哪里下载呢

**Comment by yjcaimeow** [comment]
Hi @colorful-liyu ,
The same question. The provided dataset is sdf_v1, not sdf_v1_64. 

@zjl520-l , Could you share the  sdf_v1_64 with me ?

Best,
Yingjie

**Comment by colorful-liyu** [comment]
@yjcaimeow Thanks for your concerns. We will release the preprocessed datasets in a few days.

**Comment by yjcaimeow** [comment]
Thank you so much and lookong forward to the dataset. @colorful-liyu

**Comment by colorful-liyu** [comment]
> Thank you so much and lookong forward to the dataset. @colorful-liyu

It has been uploaded in the readme.

**Comment by zjl520-l** [comment]
你好，看到了您更新的readme，但是这个onedrive的链接进不去，请问是什么情况呢。昨天进去了，下载压缩包中断了，今天就进不去了。


赵景林
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "colorful-liyu/3DQD"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月16日(星期天) 凌晨1:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [colorful-liyu/3DQD] dataset sdf_v1_64 (Issue #2)





  
Thank you so much and lookong forward to the dataset. @colorful-liyu
  
It has been uploaded in the readme.

**Comment by zjl520-l** [comment]
解决了，打扰了


赵景林
***@***.***



&nbsp;




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "colorful-liyu/3DQD"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月16日(星期天) 凌晨1:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [colorful-liyu/3DQD] dataset sdf_v1_64 (Issue #2)





  
Thank you so much and lookong forward to the dataset. @colorful-liyu
  
It has been uploaded in the readme.
