### ISSUE TITLE
When will the (demo) code for image-to-3D be released?

### ISSUE THREAD

**Issue by watarungurunnn** [colorful-liyu/3DQD#3]
Hello. Thank you for the great work!
I want to use the single-image 3D reconstruction model. When will you release the code for image-to-3D reconstruction?
And, could you release the demo for reconstruction from an arbitrary image at the same time? Thank you!

**Comment by colorful-liyu** [comment]
Thank you for your attention. We plan to release the demo code in August for I'm busy with another work now.

**Comment by colorful-liyu** [comment]
We have released the demo for single-image 3D reconstruction now.
