### ISSUE TITLE
Where can I find the part of code about MFM(Multi-Frequency Module)?

### ISSUE THREAD

**Issue by Zixunnn** [colorful-liyu/3DQD#7]
Hi, I'm studying the paper 3DQD, and I'm interested in the part called MFM. But I cannot find the specific code in this project. Could you tell me where this part of code is located? Appreciate for your help!

**Comment by colorful-liyu** [comment]
Hi, it's here! *models/networks/transformer_networks/diff_transformer/transformer_utils.py*
