### ISSUE TITLE
Would you mind sharing the tensorboard of training stage?

### ISSUE THREAD

**Issue by OswaldoBornemann** [colorful-liyu/3DQD#8]
Would you mind sharing the tensorboard of your vqvae training stage?

**Comment by colorful-liyu** [comment]
We have tried to fine-tune the vqvae, but little performance improvement is observed. So we recommend you to download the pretrained VQVAE released by AutoSDF, which is also used by us.

**Comment by colorful-liyu** [comment]
BTW, the vqvae ckpt offered by us is also the pretrained version from AutoSDF. Thanks for their work.

**Comment by OswaldoBornemann** [comment]
Thanks a lot.
